name = "njmtech-snipurl"
account_id = "c2db456075f9ab9579ff7bb76674a984"
compatibility_date = "2024-04-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "njmtech-snipurl"
database_id = "3e6ac946-1f65-4f47-a8fd-0e00f7a74302"
migrations_dir = "prisma/migrations"
